sudo: required
services:
  - docker

before_install:
  - docker build -t flobady/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run flobady/react-test npm test -- --coverage

after_success:
  - docker build -t flobady/multi-client ./client
  - docker build -t flobady/multi-nginx ./nginx
  - docker build -t flobady/multi-server ./server
  - docker build -t flobady/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to DockerHub
  - docker push flobady/multi-client
  - docker push flobady/multi-nginx
  - docker push flobady/multi-server
  - docker push flobady/multi-worker


deploy:
  provider: elasticbeanstalk
  region: us-east-2 # cf sur ElasticBeanstalk URL
  app: multi-docker # cf sur ElasticBeanstalk
  env: MultiDocker-env-1 # cf sur ElasticBeanstalk
  bucket_name: elasticbeanstalk-us-east-2-948493793866 # // services s3 copier le bucket name
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

