FROM nginx // on prend nginx comme base image
COPY ./default.conf /etc/nginx/conf.d/default.conf // on copie notre unique fichier dans le répertoire du container qui va bien pour que le container nginx fonctionne bien (cf doc en ligne)
